train_csv: "data/train.csv"
test_csv: "data/test.csv"

fixed_height: 32     
font_size: 24       
font_path: "/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf"

batch_size: 16   
num_workers: 4      