project_name: "PixelUnderstanding"
experiment_name: "pix2pix"
save_dir: "checkpoints/pix2pix4"

epochs: 60          
lr: 0.0002        
min_lr: 0.00001     
weight_decay: 0.0001  
warmup_epochs: 5    
weight_pixel: 50.0

model_name: "pix2pix"  