project_name: "PixelUnderstanding"
experiment_name: "baseline_cnn_v1"
save_dir: "checkpoints/baseline"

epochs: 50         
lr: 0.001            
min_lr: 0.00001      
weight_decay: 0.0001
warmup_epochs: 5    

model_name: "baseline_encoder_decoder"