project_name: "PixelUnderstanding"
experiment_name: "multihead_v2"
save_dir: "checkpoints/multihead"

epochs: 60          
lr: 0.0002        
min_lr: 0.00001     
weight_decay: 0.01  
warmup_epochs: 5    

model_name: "multiheadv2"  